"""add attempt question_snapshot

Revision ID: 3ae491c91297
Revises: 7e34f08ddbc0
Create Date: 2026-07-24 00:18:14.652263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ae491c91297'
down_revision: Union[str, Sequence[str], None] = '7e34f08ddbc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attempts', sa.Column('question_snapshot', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attempts', 'question_snapshot')
    # ### end Alembic commands ###
